"""Drift detector for the hypofuse public API surface.

Asserts that ``sorted(hypofuse.__all__)`` matches the golden list below.
When a new symbol is added to (or removed from) ``__init__.__all__``,
this test will fail, prompting the developer to update the golden list
and confirm the change is intentional.
"""

from __future__ import annotations

import hypofuse
from hypofuse import _version

GOLDEN: list[str] = [
    "Alignment",
    "AlignmentCosts",
    "AlignmentError",
    "AlignmentOp",
    "Arc",
    "CalibrationBin",
    "CalibrationError",
    "ComparisonRow",
    "ConfusionNetwork",
    "ConfusionSlot",
    "CorpusRates",
    "DuplicateIdError",
    "ErrorBreakdown",
    "FixtureConfig",
    "FixtureUtterance",
    "FusionArc",
    "FusionConfig",
    "FusionError",
    "FusionResult",
    "FusionRun",
    "GroupBiasRow",
    "HypofuseError",
    "HypofuseRunConfig",
    "ItnConfig",
    "KNOWN_SCHEMAS",
    "LanguageModelError",
    "LogisticCalibrator",
    "ManifestSummary",
    "MixtureLM",
    "NBestHypothesis",
    "NBestList",
    "NgramLM",
    "NormalizationConfig",
    "PRESETS",
    "ReferenceTranscript",
    "ReliabilityCurve",
    "ReportRecord",
    "RunMetadata",
    "SCHEMA_FUSION_RUN",
    "SCHEMA_NBEST",
    "SCHEMA_REFERENCE",
    "SCHEMA_REPORT",
    "SCHEMA_SYSTEM",
    "SCHEMA_VERSION",
    "SCHEMA_VERSIONS",
    "SchemaError",
    "ScoredHypothesis",
    "SliceMetric",
    "SystemMetadata",
    "TimingAlignmentStep",
    "TimingReport",
    "TimingTrack",
    "TokenGrid",
    "TokenTiming",
    "UtteranceScore",
    "VocabCoverage",
    "__version__",
    "agreement_confidence",
    "align_timings",
    "alignment_from_jsonl_row",
    "alignment_to_jsonl_row",
    "alignment_to_markdown",
    "as_manifest_dicts",
    "brier_score",
    "build_confusion_network",
    "calibrate",
    "calibration_report",
    "calibration_report_to_json",
    "capture",
    "character_error_rate",
    "confusion_from_json",
    "confusion_from_manifest_row",
    "confusion_to_json",
    "confusion_to_manifest_row",
    "consistent_with_rover",
    "convert_row",
    "corpus_error_rate",
    "corpus_error_rates",
    "describe",
    "digits_to_words",
    "duration_buckets",
    "edit_alignment",
    "embed",
    "en_phrase_to_digits",
    "en_words_to_int",
    "error_breakdown",
    "expected_calibration_error",
    "fingerprint_files",
    "fit_logistic",
    "fit_temperature",
    "fuse",
    "fusion_invariants",
    "fusion_run_from_row",
    "fusion_run_to_row",
    "generate_fixture",
    "grid_coverage",
    "grid_determinism_check",
    "grid_is_consistent",
    "grid_row",
    "group_bias_table",
    "int_to_en_words",
    "int_to_zh_words",
    "interpolate_gaps",
    "lm_weight_monotonicity",
    "lm_weight_sweep",
    "log_loss",
    "migrate_manifest",
    "migrate_row",
    "minimal_cut_one_best",
    "nbest_from_row",
    "nbest_to_row",
    "normalization_report",
    "normalize",
    "normalize_audio_path",
    "normalize_pair",
    "paired_bootstrap_ci",
    "paired_bootstrap_p_value",
    "piecewise_calibrate",
    "preserves_ranking",
    "preset",
    "progressive_align",
    "read_jsonl",
    "read_manifest",
    "reference_from_row",
    "reference_to_row",
    "reject_duplicate_ids",
    "reliability_bins",
    "reliability_curve",
    "report_from_row",
    "report_to_jsonl",
    "report_to_markdown",
    "report_to_row",
    "rescore_lm",
    "rescore_nbest",
    "rover_diff",
    "safe_audio_join",
    "seeded",
    "shallow_fusion_score",
    "slice_by_duration",
    "slice_by_field",
    "slice_by_quantiles",
    "slice_metrics",
    "snap_to_grid",
    "stable_hash",
    "stamp",
    "substitution_pairs",
    "symmetric_error_rate",
    "synthetic_calibration_set",
    "system_from_row",
    "system_to_row",
    "temperature_scale",
    "timing_report",
    "token_confidence_from_posteriors",
    "tokenize",
    "utterance_confidence",
    "utterance_confidence_from_vote",
    "validate_manifest_file",
    "validate_record",
    "verify",
    "word_error_rate",
    "words_to_digits",
    "write_jsonl",
    "write_manifest",
    "zh_phrase_to_digits",
    "zh_words_to_int",
]


def test_all_matches_golden() -> None:
    """sorted(hypofuse.__all__) must equal the golden list."""
    assert sorted(hypofuse.__all__) == GOLDEN


def test_every_name_importable() -> None:
    """Every name in __all__ must resolve on the hypofuse module."""
    for name in hypofuse.__all__:
        assert hasattr(hypofuse, name), f"{name!r} not importable from hypofuse"


def test_no_private_names() -> None:
    """No name in __all__ should start with an underscore (except __version__)."""
    for name in hypofuse.__all__:
        if name == "__version__":
            continue
        assert not name.startswith("_"), f"{name!r} looks private"


def test_version_matches_internal() -> None:
    """hypofuse.__version__ must equal hypofuse._version.__version__."""
    assert hypofuse.__version__ == _version.__version__
